ARG BASE_IMAGE_TAG=latest
FROM ghcr.io/pyvista/pyvista:$BASE_IMAGE_TAG

ENV CN_TEST_2="HEY"
ENV CN_TEST_2="$CN_JUPYTER_SERVER_BASE_URL"
ENV CN_TEST_TRAME_PREFIX="$CN_JUPYTER_SERVER_BASE_URL$JUPYTERHUB_SERVICE_PREFIX/proxy/"
ENV PYVISTA_TRAME_SERVER_PROXY_PREFIX="$CN_JUPYTER_SERVER_BASE_URL$JUPYTERHUB_SERVICE_PREFIX/proxy/"

COPY . ${HOME}
WORKDIR ${HOME}
RUN pip install -r requirements.txt
