#!/bin/bash
export CN_TEST_START="$CN_JUPYTER_SERVER_BASE_URL"
export CN_TEST_TRAME_PREFIX="$CN_JUPYTER_SERVER_BASE_URL$JUPYTERHUB_SERVICE_PREFIX/proxy/"
export PYVISTA_TRAME_SERVER_PROXY_PREFIX="$CN_JUPYTER_SERVER_BASE_URL$JUPYTERHUB_SERVICE_PREFIX/proxy/"
exec "$@"
